broadcast:
  enabled: true
  # 单位：秒
  time: 300
  default-all-start: true
  messages:
    text1:
      - '&6&m                                                         '
      - '&b[服务器娘]&a群号:882535365 官网:server.torosamy.net'
      - '&6&m                                                         '
    text2:
      - '&6&m                                                         '
      - '&b[服务器娘]&a玩服千万条 和谐第一条 言行不规范 封禁直到老'
      - '&6&m                                                         '


scoreboard:
  enabled: true
  # 单位：秒
  time: 5
  default-all-start: true
  board:
    title: '&6[ &e云间幽谷 &6]'
    lines:
      - '&6&m                         '
      - '&6 ▪ &6&l名称&f:&e%player_name%'
      - '&6 ▪ &6&l等级&f:&e%player_level%'
      - '&6&m                         '
      - '&6 ▪ &6官网&f:&eserver.torosamy.net'
      - '&6 ▪ &6群号&f:&e882535365'


tab-list:
  enabled: true
  time: 5
  default-all-start: true
  header:
    - '&f&m                                   '
    - '&6云间幽谷'
    - '&e欢迎玩家:&f%player_name%'
    - '&6生存在线 &f%server_online% &6全服在线: &f%bungee_total%'
    - '&f&m                                   '
  footer:
    - '&f&m                                   '
    - '&6服主QQ:&f1364596766'
    - '&e官网:&fserver.torosamy.net'
    - '&6群号:&f882535365'
    - '&f&m                                   '
  name-list: '&6[&e%vault_prefix%&6]&f%player_name%'


bossbar:
  enabled: true
  time: 5
  default-all-start: true
  info:
    # SEGMENTED_10 将血条分为10个部分
    # SEGMENTED_12 将血条分为12个部分
    # SEGMENTED_20 将血条分为20个部分
    # SEGMENTED_6  将血条分为6个部分
    # SOLID        将血条设置为一个部分
    style: SOLID
    color: YELLOW # 仅限 1.9+ 服务器: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
    text: '&e快加群:&6882535365 &e参加公会比赛吧! ✧*｡٩(ˊᗜˋ*)و✧*｡'


join-broadcast:
  enabled: true
  title: '&6&l生存服'
  sub-title: '&e&l欢迎来到&6&l云间幽谷&e&l纯净服务器'
