broadcast:
  custom-permission: beautifyme.custom.broadcast
  enabled: true
  # 单位：秒
  time: 300
  messages:
    - - '&6&m                                                         '
      - '&b[服务器娘]&a群号:1057650878 官网:www.bitlie.net'
      - '&6&m                                                         '
    - - '&6&m                                                         '
      - '&b[服务器娘]&a玩服千万条 和谐第一条 言行不规范 封禁直到老'
      - '&6&m                                                         '


scoreboard:
  enabled: true  # 单位：秒
  time: 5
  custom-permission: beautifyme.custom.scoreboard
  board:
    title: '&6[ &eBitLie &6]'
    lines:
      - '&6&m                         '
      - '&6 ▪ &6&l世界&f:&6[&e%multiverse-core_alias%&6]'
      - '&6 ▪ &6&l公会&f:&6[&e%guild_prefix%&6]'
      - '&6 ▪ &6&l成就&f:&6[&e%deluxetags_tag%&6]'
      - '&6 ▪ &6&l称号&f:&6[&e%vault_prefix%&6]'
      - '&6 ▪ &6&l名称&f:&e%player_name%'
      - '&6 ▪ &6&l积分&f:&e%vault_eco_balance_fixed%'
      - '&6 ▪ &6&l血量&f:&e%player_health_rounded%'
      - '&6 ▪ &6&l饥饿&f:&e%player_food_level%'
      - '&6 ▪ &6&l等级&f:&e%player_level%'
      - '&6 ▪ &6&l点券&f:&e%playerpoints_points%'
      - '&6&m                         '
      - '&6 ▪ &6官网&f:&ewww.bitlie.net'
      - '&6 ▪ &6群号&f:&e1057650878'


tab-list:
  header-enabled: true
  footer-enabled: true
  name-list-enabled: true
  custom-header-permission: beautifyme.custom.header
  custom-footer-permission: beautifyme.custom.footer
  custom-name-list-permission: beautifyme.custom.name.list
  time: 5
  header:
    - '&f&m                                   '
    - '&6BitLie'
    - '&e欢迎玩家:&f%player_name%'
    - '&6生存在线 &f%server_online% &6全服在线: &f%bungee_total%'
    - '&f&m                                   '
  footer:
    - '&f&m                                   '
    - '&6服主QQ:&f1364596766'
    - '&e官网:&fwww.bitlie.net'
    - '&6群号:&f1057650878'
    - '&f&m                                   '
  name-list: '&6[&e%guild_prefix%&6]&f&r%player_name%&6[&e%vault_prefix%&6]'
  
title-big-prefix: "<gradient:#EEC4A7:#FEDCEE>"
title-small-prefix: "<gradient:#EEC4A7:#FEDCEE>"

name-tag:
  time: 5
  enabled: true
  prefix: ""
  suffix: ""
  below: ""
  custom-permission: beautifyme.custom.name.tag
bossbar:
  enabled: true
  time: 5
  info:
    # SEGMENTED_10 将血条分为10个部分
    # SEGMENTED_12 将血条分为12个部分
    # SEGMENTED_20 将血条分为20个部分
    # SEGMENTED_6  将血条分为6个部分
    # SOLID        将血条设置为一个部分
    style: SOLID
    color: YELLOW # 仅限 1.9+ 服务器: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
    text: '&e快来官网:&6www.bitlie.net &e反馈意见吧! ✧*｡٩(ˊᗜˋ*)و✧*｡'


join-broadcast:
  custom-permission: beautifyme.custom.join.broadcast
  enabled: true
  title: '&6&l生存服'
  sub-title: '&e&l欢迎来到&6&lBitLie&e&l纯净服务器'

join-message:
  custom-permission: beautifyme.custom.join.message
  enabled: true
  message: "&e玩家 &f%player_name% &e激动地加入了&6生存服"
quit-message:
  custom-permission: beautifyme.custom.quit.message
  enabled: true
  message: "&e玩家 &f%player_name% &e匆匆地离开了&6生存服"

first-join-message:
  enabled: true
  message: "&e欢迎新玩家 &f%player_name% &e第一次来到&6生存服"

join-motd:
  enabled: true
  custom-permission: beautifyme.custom.join.motd
  messages:
    - '&e&m                               '
    - '&6 ▪ &e&l服务器于 &6&l2025.11.24 &e&l更新第&6&l 1 &e&l次'
    - '&6 ▪ &e&l输入&6&l/update&e&l以查看更新'
    - '&6 ▪ &e&l输入&6&l/notice&e&l以查看活动'
    - '&e&m                               '