name: BeautifyMe
version: '2.0-SNAPSHOT'
main: net.torosamy.beautifyMe.BeautifyMe
api-version: '1.13'
authors: [ Torosamy,yweiyang ]
website: https://www.torosamy.net
depend:
  - TorosamyCore
  - PlaceholderAPI