name: EssentialYwY
version: '${project.version}'
main: net.torosamy.essentialywy.EssentialYwY
api-version: '1.20'
commands:
  essy:
    usage: /essy reload
    permission: essentialywy.reload
  wcy:
    usage: /wcy reload
    permission: essentialywy.reload.welcome
permissions:
  essentialywy.*:
    description: "All permissions of this plugin"
    default: op
  essentialywy.reload:
    description: "to reload"
    default: op
  essentialywy.reload.welcome:
    default: op
    description: "to reload welcome"