#这个配置文件关于插件描述了插件是否启用
ColorYwY:
  enabled: true
  func:
    #    计分板
    scoreboard: true
    #    广播
    broadcast: true
    #    Tab列表
    tabList: true
    bossbar: true
WelcomeYwY:
  enabled: true
  func:
    #进服大Title修改
    join-broadcast: true
    #上线\下线触发的功能是否启用
    join-event: false
    quit-event: false
    #进服欢迎奖励
    first-join-welcome: true
    first-join-event: true
TeleportYwY:
  enabled: true
  func:
    spawn: true